import Home from './Home';
import Playground from './Playground';
import SignIn from './SignIn';
import SignUp from './SignUp';
import Logout from './Logout';
import Workspaces from './Workspaces';
import Workspace, { loader as WorspaceLoader} from './Workspace';
import CreateWorkspace from './CreateWorkspace';
import Exercicedemo from './Exercicedemo';
import Exerciceliste from './Exercicesliste';
export { Home, Playground, SignIn, SignUp, Logout, Workspaces, Workspace, WorspaceLoader, CreateWorkspace, Exercicedemo, Exerciceliste };